// Repertorio de uso frecuente en la unidad (neurología del anciano, psiquiatría geriátrica y geriatría),
// con las descripciones oficiales de la CIE-10-ES 2026. [código, descripción, alias de búsqueda, marcas]
// Marcas: M manifestación (nunca principal) · N no puede ser principal · E exento de POAD.
// Se puede ampliar a mano: cualquier código del catálogo completo (public/cie10_es_2026.txt) también se encuentra.
export const FRECUENTES: [string, string, string, string][] = [
  ["G30.0", "Enfermedad de Alzheimer de comienzo temprano", "alzheimer", ""],
  ["G30.1", "Enfermedad de Alzheimer de comienzo tardío", "alzheimer", ""],
  ["G30.8", "Otros tipos de enfermedad de Alzheimer", "alzheimer", ""],
  ["G30.9", "Enfermedad de Alzheimer, no especificada", "alzheimer", ""],
  ["G31.01", "Enfermedad de Pick", "demencia frontotemporal", ""],
  ["G31.09", "Otro trastorno neurocognitivo frontotemporal", "DFT", ""],
  ["G31.83", "Trastorno neurocognitivo por cuerpos de Lewy", "demencia cuerpos de lewy DCL", ""],
  ["G31.84", "Deterioro cognitivo leve de etiología incierta o desconocida", "DCL leve", ""],
  ["G31.85", "Degeneración corticobasal", "DCB", ""],
  ["G31.1", "Degeneración cerebral senil no clasificada bajo otro concepto", "", ""],
  ["G31.89", "Otras enfermedades degenerativas especificadas del sistema nervioso", "", ""],
  ["G31.9", "Enfermedad degenerativa del sistema nervioso, no especificada", "", ""],
  ["G20.A1", "Enfermedad de Parkinson sin discinesia, sin mención de fluctuaciones", "parkinson", ""],
  ["G20.A2", "Enfermedad de Parkinson sin discinesia, con fluctuaciones", "parkinson", ""],
  ["G20.B1", "Enfermedad de Parkinson con discinesia, sin mención de fluctuaciones", "parkinson", ""],
  ["G20.B2", "Enfermedad de Parkinson con discinesia, con fluctuaciones", "parkinson", ""],
  ["G20.C", "Parkinsonismo, no especificado", "parkinson", ""],
  ["G21.11", "Parkinsonismo inducido por neurolépticos", "parkinsonismo farmacológico", ""],
  ["G21.19", "Parkinsonismo secundario inducido por otros fármacos", "parkinsonismo farmacológico", ""],
  ["G23.1", "Oftalmoplejia supranuclear progresiva [Steele-Richardson-Olszewski]", "PSP", ""],
  ["G10", "Enfermedad de Huntington", "corea", ""],
  ["G12.21", "Esclerosis lateral amiotrófica", "ELA", ""],
  ["G91.2", "Hidrocefalia normotensiva (idiopática)", "HPN hidrocefalia", ""],
  ["G25.0", "Temblor esencial", "", ""],
  ["A81.00", "Enfermedad de Creutzfeldt-Jakob, no especificada", "ECJ prion", ""],
  ["F04", "Trastorno amnésico debido a afección fisiológica conocida", "amnesia korsakoff", ""],
  ["F10.26", "Dependencia de alcohol, con trastorno amnésico persistente inducido por alcohol", "korsakoff", ""],
  ["F10.27", "Dependencia de alcohol, con demencia persistente inducida por alcohol", "demencia alcohólica", ""],
  ["E51.2", "Encefalopatía de Wernicke", "wernicke", ""],
  ["F06.70", "Trastorno neurocognitivo leve debido a una afección fisiológica conocida sin alteración del comportamiento", "DCL", ""],
  ["F06.71", "Trastorno neurocognitivo leve debido a una afección fisiológica conocida con alteración del comportamiento", "DCL", ""],
  ["F05", "Delirio debido a afección fisiológica conocida", "delirium síndrome confusional agudo", ""],
  ["R41.81", "Deterioro cognitivo relacionado con la edad", "", ""],
  ["R41.0", "Desorientación, no especificada", "", ""],
  ["R41.3", "Otra amnesia", "pérdida de memoria", ""],
  ["R41.82", "Estado mental alterado, no especificado", "", ""],
  ["G93.40", "Encefalopatía, no especificada", "", ""],
  ["G93.41", "Encefalopatía metabólica", "", ""],
  ["G93.49", "Otros tipos de encefalopatía", "", ""],
  ["I63.9", "Infarto cerebral, no especificado", "ictus ACV", ""],
  ["I61.9", "Hemorragia intracerebral no traumática, no especificada", "ictus hemorrágico", ""],
  ["I62.9", "Hemorragia intracraneal no traumática, no especificada", "", ""],
  ["I62.00", "Hemorragia subdural no traumática, no especificada", "hematoma subdural", ""],
  ["G45.9", "Accidente isquémico cerebral transitorio, no especificado", "AIT", ""],
  ["I67.2", "Aterosclerosis cerebral", "", ""],
  ["I67.3", "Leucoencefalopatía vascular progresiva", "binswanger leucoaraiosis", ""],
  ["I69.30", "Secuelas no especificadas de infarto cerebral", "secuelas ictus", "E"],
  ["I69.320", "Afasia tras infarto cerebral", "secuelas ictus", "E"],
  ["I69.398", "Otras secuelas de infarto cerebral", "secuelas ictus", "E"],
  ["G40.909", "Epilepsia, no especificada, no intratable, sin estado de mal epiléptico", "crisis convulsivas", ""],
  ["R45.1", "Inquietud y agitación", "agitación", ""],
  ["R45.4", "Irritabilidad e ira", "", ""],
  ["R45.6", "Comportamiento violento", "agresividad", ""],
  ["R45.851", "Ideaciones suicidas", "", ""],
  ["R44.3", "Alucinaciones, no especificadas", "", ""],
  ["R44.0", "Alucinaciones auditivas", "", ""],
  ["R44.1", "Alucinaciones visuales", "", ""],
  ["R46.89", "Otros síntomas y signos que afectan a la apariencia y al comportamiento", "", ""],
  ["G47.00", "Insomnio, no especificado", "", ""],
  ["F51.01", "Insomnio primario", "", ""],
  ["G47.52", "Trastorno de comportamiento del sueño REM", "TCSR", ""],
  ["G47.33", "Apnea obstructiva del sueño (del adulto) (pediátrica)", "SAOS", ""],
  ["R40.0", "Somnolencia", "", ""],
  ["F06.0", "Trastorno psicótico con alucinaciones debido a afección fisiológica conocida", "alucinosis orgánica", ""],
  ["F06.2", "Trastorno psicótico con ideas delirantes debido a afección fisiológica conocida", "delirante orgánico", ""],
  ["F06.30", "Trastorno del estado de ánimo debido a afección fisiológica conocida, no especificado", "", ""],
  ["F06.31", "Trastorno del estado de ánimo debido a afección fisiológica conocida con rasgos depresivos", "", ""],
  ["F06.32", "Trastorno del estado de ánimo debido a afección fisiológica conocida con episodio de tipo depresivo mayor", "", ""],
  ["F06.33", "Trastorno del estado de ánimo debido a afección fisiológica conocida con rasgos maníacos", "", ""],
  ["F06.34", "Trastorno del estado de ánimo debido a afección fisiológica conocida con rasgos mixtos", "", ""],
  ["F06.4", "Trastorno de ansiedad debido a afección fisiológica conocida", "", ""],
  ["F06.8", "Otros trastornos mentales especificados debidos a afecciones fisiológicas conocidas", "", ""],
  ["F07.0", "Alteración de personalidad debida a afección fisiológica conocida", "orgánico personalidad", ""],
  ["F09", "Trastorno mental no especificado debido a afección fisiológica conocida", "", ""],
  ["F20.0", "Esquizofrenia paranoide", "", ""],
  ["F20.9", "Esquizofrenia, no especificada", "", ""],
  ["F22", "Trastornos delirantes", "trastorno delirante paranoia", ""],
  ["F25.0", "Trastorno esquizoafectivo, tipo bipolar", "", ""],
  ["F25.1", "Trastorno esquizoafectivo, tipo depresivo", "", ""],
  ["F25.9", "Trastorno esquizoafectivo, no especificado", "", ""],
  ["F29", "Psicosis no especificada no debida a sustancia o afección fisiológica conocidas", "psicosis", ""],
  ["F30.9", "Episodio maníaco, no especificado", "manía", ""],
  ["F31.9", "Trastorno bipolar, no especificado", "bipolar", ""],
  ["F32.0", "Trastorno depresivo mayor, episodio único, leve", "depresión", ""],
  ["F32.1", "Trastorno depresivo mayor, episodio único, moderado", "depresión", ""],
  ["F32.2", "Trastorno depresivo mayor, episodio único, grave sin síntomas psicóticos", "depresión", ""],
  ["F32.3", "Trastorno depresivo mayor, episodio único, grave con síntomas psicóticos", "depresión", ""],
  ["F32.4", "Trastorno depresivo mayor, episodio único, en remisión parcial", "depresión", ""],
  ["F32.5", "Trastorno depresivo mayor, episodio único, en remisión completa", "depresión", ""],
  ["F32.9", "Trastorno depresivo mayor, episodio único, no especificado", "depresión", ""],
  ["F32.A", "Depresión, no especificada", "depresión", ""],
  ["F33.0", "Trastorno depresivo mayor, recurrente, leve", "depresión", ""],
  ["F33.1", "Trastorno depresivo mayor, recurrente, moderado", "depresión", ""],
  ["F33.2", "Trastorno depresivo mayor, recurrente grave sin rasgos psicóticos", "depresión", ""],
  ["F33.3", "Trastorno depresivo mayor, recurrente grave con síntomas psicóticos", "depresión", ""],
  ["F33.9", "Trastorno depresivo mayor, recurrente, no especificado", "depresión", ""],
  ["F34.1", "Trastorno distímico", "distimia", ""],
  ["F41.0", "Trastorno de pánico [ansiedad episódica paroxística]", "", ""],
  ["F41.1", "Trastorno de ansiedad generalizada", "", ""],
  ["F41.8", "Otros trastornos de ansiedad especificados", "mixto ansioso depresivo", ""],
  ["F41.9", "Trastorno de ansiedad, no especificado", "", ""],
  ["F42.9", "Trastorno obsesivo-compulsivo, no especificado", "TOC", ""],
  ["F43.10", "Trastorno por estrés postraumático, no especificado", "TEPT", ""],
  ["F43.20", "Trastorno adaptativo, no especificado", "", ""],
  ["F43.21", "Trastorno adaptativo con estado de ánimo depresivo", "", ""],
  ["F43.22", "Trastorno adaptativo con ansiedad", "", ""],
  ["F43.23", "Trastorno adaptativo mixto, con ansiedad y depresión", "", ""],
  ["F60.9", "Trastorno de personalidad, no especificado", "", ""],
  ["F79", "Discapacidad intelectual no especificada", "retraso mental", ""],
  ["F10.20", "Dependencia de alcohol, sin complicaciones", "alcoholismo", ""],
  ["F13.20", "Dependencia de sedantes, hipnóticos o ansiolíticos, sin complicaciones", "benzodiacepinas", ""],
  ["R54", "Debilidad física relacionada con edad", "fragilidad senilidad", ""],
  ["M62.84", "Sarcopenia", "", ""],
  ["M62.81", "Debilidad muscular (generalizada)", "", ""],
  ["R26.81", "Inestabilidad en bipedestación", "", ""],
  ["R26.89", "Otras alteraciones de la marcha y de la movilidad", "", ""],
  ["R26.2", "Dificultad para caminar, no clasificada bajo otro concepto", "", ""],
  ["R29.6", "Caídas repetidas", "caídas", ""],
  ["Z91.81", "Historia personal de caída", "caídas", "NE"],
  ["W19.XXXA", "Caída no especificada, contacto inicial", "caída", "N"],
  ["R13.10", "Disfagia, no especificada", "", ""],
  ["R13.12", "Disfagia, fase orofaríngea", "", ""],
  ["R63.4", "Pérdida anormal de peso", "", ""],
  ["R63.6", "Peso inferior al normal", "", ""],
  ["R63.0", "Anorexia", "", ""],
  ["R64", "Caquexia", "", ""],
  ["E46", "Malnutrición calórico-proteica no especificada", "desnutrición", ""],
  ["E86.0", "Deshidratación", "", ""],
  ["R32", "Incontinencia urinaria no especificada", "", ""],
  ["R15.9", "Incontinencia total de heces", "", ""],
  ["R53.81", "Otros tipos de malestar", "", ""],
  ["R53.1", "Astenia", "", ""],
  ["R55", "Síncope y colapso", "", ""],
  ["I95.1", "Hipotensión ortostática", "", ""],
  ["R52", "Dolor, no especificado", "", ""],
  ["G89.29", "Otro dolor crónico", "", ""],
  ["Z74.01", "Situación de confinamiento en cama", "", "NE"],
  ["Z74.09", "Otro tipo de movilidad reducida", "", "N"],
  ["Z74.1", "Necesidad de asistencia con cuidado personal", "", "N"],
  ["Z74.2", "Necesidad de asistencia en el hogar sin otro miembro de la familia que pueda prestar cuidados", "", "N"],
  ["Z74.3", "Necesidad de supervisión continua", "", "N"],
  ["Z99.3", "Dependencia a silla de ruedas", "", "NE"],
  ["Z99.81", "Dependencia de oxígeno suplementario", "", "NE"],
  ["Z60.2", "Problemas relacionados con vivir solo", "", ""],
  ["Z63.6", "Familiar dependiente que requiere cuidados en el hogar", "", "NE"],
  ["Z66", "No reanimación cardiopulmonar", "NO RCP", "N"],
  ["Z51.5", "Contacto para cuidados paliativos", "paliativos", "E"],
  ["Z79.01", "Uso prolongado (actual) de anticoagulantes", "sintrom anticoagulación", "E"],
  ["Z79.899", "Otra terapia prolongada (actual) con medicamentos", "polifarmacia", "NE"],
  ["I10", "Hipertensión esencial (primaria)", "HTA", ""],
  ["I11.9", "Enfermedad cardiaca hipertensiva sin insuficiencia cardiaca", "", ""],
  ["I25.10", "Enfermedad cardiaca aterosclerótica de arteria coronaria nativa sin angina de pecho", "cardiopatía isquémica", ""],
  ["I48.91", "Fibrilación auricular no especificada", "FA", ""],
  ["I48.0", "Fibrilación paroxística auricular", "FA", ""],
  ["I48.21", "Fibrilación auricular permanente", "FA", ""],
  ["I50.9", "Insuficiencia cardiaca, no especificada", "ICC", ""],
  ["I73.9", "Enfermedad vascular periférica, no especificada", "", ""],
  ["I87.2", "Insuficiencia venosa (crónica) (periférica)", "", ""],
  ["E11.9", "Diabetes mellitus tipo 2 sin complicaciones", "DM2", ""],
  ["E11.65", "Diabetes mellitus tipo 2 con hiperglucemia", "DM2", ""],
  ["E78.00", "Hipercolesterolemia pura, no especificada", "", ""],
  ["E78.5", "Hiperlipidemia, no especificada", "dislipemia", ""],
  ["E66.9", "Obesidad, no especificada", "", ""],
  ["E03.9", "Hipotiroidismo, no especificado", "", ""],
  ["E55.9", "Carencia de vitamina D, no especificada", "", ""],
  ["E53.8", "Carencia de otras vitaminas del grupo B especificadas", "déficit B12", ""],
  ["D51.9", "Anemia por carencia de vitamina B12, no especificada", "", ""],
  ["D50.9", "Anemia ferropénica, no especificada", "ferropenia", ""],
  ["D64.9", "Anemia, no especificada", "", ""],
  ["E87.1", "Hiposmolaridad e hiponatremia", "hiponatremia", ""],
  ["E87.6", "Hipopotasemia", "", ""],
  ["E87.5", "Hiperpotasemia", "", ""],
  ["J18.9", "Neumonía, microorganismo no especificado", "", ""],
  ["J69.0", "Neumonitis debida a inhalación de alimentos y vómito", "broncoaspiración neumonía aspirativa aspiración", ""],
  ["J44.1", "Enfermedad pulmonar obstructiva crónica con exacerbación (aguda)", "EPOC", ""],
  ["J44.9", "Enfermedad pulmonar obstructiva crónica, no especificada", "EPOC", ""],
  ["J20.9", "Bronquitis aguda, no especificada", "", ""],
  ["J96.01", "Insuficiencia respiratoria aguda con hipoxia", "", ""],
  ["J96.10", "Insuficiencia respiratoria crónica no especificada si con hipoxia o con hipercapnia", "", ""],
  ["U07.1", "COVID-19", "coronavirus", ""],
  ["A41.9", "Sepsis, microorganismo no especificado", "", ""],
  ["A09", "Gastroenteritis y colitis infecciosas, no especificadas", "", ""],
  ["A04.72", "Enterocolitis debida a Clostridium difficile, no especificada como recurrente", "c difficile", ""],
  ["B02.9", "Herpes zóster sin complicaciones", "", ""],
  ["L03.90", "Celulitis, no especificada", "", ""],
  ["N39.0", "Infección de tracto urinario, localización no especificada", "ITU", ""],
  ["N30.00", "Cistitis aguda sin hematuria", "", ""],
  ["N40.0", "Hiperplasia prostática benigna sin síntomas de tracto urinario inferior", "HBP", ""],
  ["N40.1", "Hiperplasia prostática benigna con síntomas de tracto urinario inferior", "HBP", ""],
  ["N18.30", "Enfermedad renal crónica, estadio 3 no especificado", "ERC", ""],
  ["N18.9", "Enfermedad renal crónica, no especificada", "ERC", ""],
  ["N17.9", "Fallo renal agudo, no especificado", "", ""],
  ["R33.9", "Retención urinaria, no especificada", "", ""],
  ["K59.00", "Estreñimiento, no especificado", "", ""],
  ["K56.41", "Impactación fecal", "fecaloma", ""],
  ["K21.9", "Enfermedad por reflujo gastroesofágico sin esofagitis", "ERGE", ""],
  ["K92.2", "Hemorragia gastrointestinal, no especificada", "", ""],
  ["M81.0", "Osteoporosis relacionada con la edad, sin fractura patológica actual", "", ""],
  ["M80.08XA", "Osteoporosis relacionada con la edad con fractura patológica actual, vértebra(-s), contacto inicial por fractura", "aplastamiento vertebral", ""],
  ["S72.001A", "Fractura de parte no especificada del cuello de fémur derecho, contacto inicial por fractura cerrada", "fractura cadera", ""],
  ["S72.002A", "Fractura de parte no especificada del cuello de fémur izquierdo, contacto inicial por fractura cerrada", "fractura cadera", ""],
  ["S72.141A", "Fractura intertrocantérea desplazada de fémur derecho, contacto inicial por fractura cerrada", "fractura cadera", ""],
  ["S72.142A", "Fractura intertrocantérea desplazada de fémur izquierdo, contacto inicial por fractura cerrada", "fractura cadera", ""],
  ["M16.9", "Artrosis de cadera no especificada", "", ""],
  ["M17.9", "Artrosis de rodilla no especificada", "", ""],
  ["M19.90", "Artrosis no especificada, localización no especificada", "", ""],
  ["M54.50", "Dolor en la parte inferior de la espalda, no especificado", "lumbalgia", ""],
  ["H91.90", "Pérdida de audición no especificada, oído no especificado", "hipoacusia", ""],
  ["H54.7", "Pérdida de visión no especificada", "", ""],
  ["H25.9", "Catarata senil, no especificada", "", ""],
  ["C61", "Neoplasia maligna de próstata", "", ""],
  ["C18.9", "Neoplasia maligna de colon, no especificada", "", ""],
  ["C34.90", "Neoplasia maligna de parte no especificada, bronquio o pulmón no especificados", "", ""],
  ["C79.31", "Neoplasia maligna secundaria de cerebro", "metástasis cerebral", ""],
  ["D32.0", "Neoplasia benigna de meninges cerebrales", "meningioma", ""],
  ["F01.50", "Demencia vascular, gravedad no especificada, sin alteración del comportamiento, alteración psicótica, alteración del estado de ánimo ni ansiedad", "demencia vascular", ""],
  ["F01.511", "Demencia vascular, gravedad no especificada, con agitación", "demencia vascular agitación", ""],
  ["F01.518", "Demencia vascular, gravedad no especificada, con otro tipo de alteración del comportamiento", "demencia vascular conducta", ""],
  ["F01.52", "Demencia vascular, gravedad no especificada, con alteración psicótica", "demencia vascular psicosis delirios alucinaciones", ""],
  ["F01.53", "Demencia vascular, gravedad no especificada, con alteración del estado de ánimo", "demencia vascular depresión", ""],
  ["F01.54", "Demencia vascular, gravedad no especificada, con ansiedad", "demencia vascular ansiedad", ""],
  ["F01.A0", "Demencia vascular, leve, sin alteración del comportamiento, alteración psicótica, alteración del estado de ánimo ni ansiedad", "demencia vascular", ""],
  ["F01.A11", "Demencia vascular, leve, con agitación", "demencia vascular agitación", ""],
  ["F01.A18", "Demencia vascular, leve, con otro tipo de alteración del comportamiento", "demencia vascular conducta", ""],
  ["F01.A2", "Demencia vascular, leve, con alteración psicótica", "demencia vascular psicosis delirios alucinaciones", ""],
  ["F01.A3", "Demencia vascular, leve, con alteración del estado de ánimo", "demencia vascular depresión", ""],
  ["F01.A4", "Demencia vascular, leve, con ansiedad", "demencia vascular ansiedad", ""],
  ["F01.B0", "Demencia vascular, moderada, sin alteración del comportamiento, alteración psicótica, alteración del estado de ánimo ni ansiedad", "demencia vascular", ""],
  ["F01.B11", "Demencia vascular, moderada, con agitación", "demencia vascular agitación", ""],
  ["F01.B18", "Demencia vascular, moderada, con otro tipo de alteración del comportamiento", "demencia vascular conducta", ""],
  ["F01.B2", "Demencia vascular, moderada, con alteración psicótica", "demencia vascular psicosis delirios alucinaciones", ""],
  ["F01.B3", "Demencia vascular, moderada, con alteración del estado de ánimo", "demencia vascular depresión", ""],
  ["F01.B4", "Demencia vascular, moderada, con ansiedad", "demencia vascular ansiedad", ""],
  ["F01.C0", "Demencia vascular, grave, sin alteración del comportamiento, alteración psicótica, alteración del estado de ánimo ni ansiedad", "demencia vascular", ""],
  ["F01.C11", "Demencia vascular, grave, con agitación", "demencia vascular agitación", ""],
  ["F01.C18", "Demencia vascular, grave, con otro tipo de alteración del comportamiento", "demencia vascular conducta", ""],
  ["F01.C2", "Demencia vascular, grave, con alteración psicótica", "demencia vascular psicosis delirios alucinaciones", ""],
  ["F01.C3", "Demencia vascular, grave, con alteración del estado de ánimo", "demencia vascular depresión", ""],
  ["F01.C4", "Demencia vascular, grave, con ansiedad", "demencia vascular ansiedad", ""],
  ["F02.80", "Demencia en otras enfermedades clasificadas bajo otro concepto, gravedad no especificada, sin alteración del comportamiento, alteración psicótica, alteración del estado de ánimo ni ansiedad", "demencia alzheimer parkinson lewy", "MN"],
  ["F02.811", "Demencia en otras enfermedades clasificadas bajo otro concepto, gravedad no especificada, con agitación", "demencia alzheimer parkinson lewy agitación", "MN"],
  ["F02.818", "Demencia en otras enfermedades clasificadas bajo otro concepto, gravedad no especificada, con otro tipo de alteración del comportamiento", "demencia alzheimer parkinson lewy conducta", "MN"],
  ["F02.82", "Demencia en otras enfermedades clasificadas bajo otro concepto, gravedad no especificada, con alteración psicótica", "demencia alzheimer parkinson lewy psicosis delirios alucinaciones", "MN"],
  ["F02.83", "Demencia en otras enfermedades clasificadas bajo otro concepto, gravedad no especificada, con alteración del estado de ánimo", "demencia alzheimer parkinson lewy depresión", "MN"],
  ["F02.84", "Demencia en otras enfermedades clasificadas bajo otro concepto, gravedad no especificada, con ansiedad", "demencia alzheimer parkinson lewy ansiedad", "MN"],
  ["F02.A0", "Demencia en otras enfermedades clasificadas bajo otro concepto, leve, sin alteración del comportamiento, alteración psicótica, alteración del estado de ánimo ni ansiedad", "demencia alzheimer parkinson lewy", "MN"],
  ["F02.A11", "Demencia en otras enfermedades clasificadas bajo otro concepto, leve, con agitación", "demencia alzheimer parkinson lewy agitación", "MN"],
  ["F02.A18", "Demencia en otras enfermedades clasificadas bajo otro concepto, leve, con otro tipo de alteración del comportamiento", "demencia alzheimer parkinson lewy conducta", "MN"],
  ["F02.A2", "Demencia en otras enfermedades clasificadas bajo otro concepto, leve, con alteración psicótica", "demencia alzheimer parkinson lewy psicosis delirios alucinaciones", "MN"],
  ["F02.A3", "Demencia en otras enfermedades clasificadas bajo otro concepto, leve, con alteración del estado de ánimo", "demencia alzheimer parkinson lewy depresión", "MN"],
  ["F02.A4", "Demencia en otras enfermedades clasificadas bajo otro concepto, leve, con ansiedad", "demencia alzheimer parkinson lewy ansiedad", "MN"],
  ["F02.B0", "Demencia en otras enfermedades clasificadas bajo otro concepto, moderada, sin alteración del comportamiento, alteración psicótica, alteración del estado de ánimo ni ansiedad", "demencia alzheimer parkinson lewy", "MN"],
  ["F02.B11", "Demencia en otras enfermedades clasificadas bajo otro concepto, moderada, con agitación", "demencia alzheimer parkinson lewy agitación", "MN"],
  ["F02.B18", "Demencia en otras enfermedades clasificadas bajo otro concepto, moderada, con otro tipo de alteración del comportamiento", "demencia alzheimer parkinson lewy conducta", "MN"],
  ["F02.B2", "Demencia en otras enfermedades clasificadas bajo otro concepto, moderada, con alteración psicótica", "demencia alzheimer parkinson lewy psicosis delirios alucinaciones", "MN"],
  ["F02.B3", "Demencia en otras enfermedades clasificadas bajo otro concepto, moderada, con alteración del estado de ánimo", "demencia alzheimer parkinson lewy depresión", "MN"],
  ["F02.B4", "Demencia en otras enfermedades clasificadas bajo otro concepto, moderada, con ansiedad", "demencia alzheimer parkinson lewy ansiedad", "MN"],
  ["F02.C0", "Demencia en otras enfermedades clasificadas bajo otro concepto, grave, sin alteración del comportamiento, alteración psicótica, alteración del estado de ánimo ni ansiedad", "demencia alzheimer parkinson lewy", "MN"],
  ["F02.C11", "Demencia en otras enfermedades clasificadas bajo otro concepto, grave, con agitación", "demencia alzheimer parkinson lewy agitación", "MN"],
  ["F02.C18", "Demencia en otras enfermedades clasificadas bajo otro concepto, grave, con otro tipo de alteración del comportamiento", "demencia alzheimer parkinson lewy conducta", "MN"],
  ["F02.C2", "Demencia en otras enfermedades clasificadas bajo otro concepto, grave, con alteración psicótica", "demencia alzheimer parkinson lewy psicosis delirios alucinaciones", "MN"],
  ["F02.C3", "Demencia en otras enfermedades clasificadas bajo otro concepto, grave, con alteración del estado de ánimo", "demencia alzheimer parkinson lewy depresión", "MN"],
  ["F02.C4", "Demencia en otras enfermedades clasificadas bajo otro concepto, grave, con ansiedad", "demencia alzheimer parkinson lewy ansiedad", "MN"],
  ["F03.90", "Demencia no especificada, gravedad no especificada, sin alteración del comportamiento, alteración psicótica, alteración del estado de ánimo ni ansiedad", "demencia", ""],
  ["F03.911", "Demencia no especificada, gravedad no especificada, con agitación", "demencia agitación", ""],
  ["F03.918", "Demencia no especificada, gravedad no especificada, con otro tipo de alteración del comportamiento", "demencia conducta", ""],
  ["F03.92", "Demencia no especificada, gravedad no especificada, con alteración psicótica", "demencia psicosis delirios alucinaciones", ""],
  ["F03.93", "Demencia no especificada, gravedad no especificada, con alteración del estado de ánimo", "demencia depresión", ""],
  ["F03.94", "Demencia no especificada, gravedad no especificada, con ansiedad", "demencia ansiedad", ""],
  ["F03.A0", "Demencia no especificada, leve, sin alteración del comportamiento, alteración psicótica, alteración del estado de ánimo ni ansiedad", "demencia", ""],
  ["F03.A11", "Demencia no especificada, leve, con agitación", "demencia agitación", ""],
  ["F03.A18", "Demencia no especificada, leve, con otro tipo de alteración del comportamiento", "demencia conducta", ""],
  ["F03.A2", "Demencia no especificada, leve, con alteración psicótica", "demencia psicosis delirios alucinaciones", ""],
  ["F03.A3", "Demencia no especificada, leve, con alteración del estado de ánimo", "demencia depresión", ""],
  ["F03.A4", "Demencia no especificada, leve, con ansiedad", "demencia ansiedad", ""],
  ["F03.B0", "Demencia no especificada, moderada, sin alteración del comportamiento, alteración psicótica, alteración del estado de ánimo ni ansiedad", "demencia", ""],
  ["F03.B11", "Demencia no especificada, moderada, con agitación", "demencia agitación", ""],
  ["F03.B18", "Demencia no especificada, moderada, con otro tipo de alteración del comportamiento", "demencia conducta", ""],
  ["F03.B2", "Demencia no especificada, moderada, con alteración psicótica", "demencia psicosis delirios alucinaciones", ""],
  ["F03.B3", "Demencia no especificada, moderada, con alteración del estado de ánimo", "demencia depresión", ""],
  ["F03.B4", "Demencia no especificada, moderada, con ansiedad", "demencia ansiedad", ""],
  ["F03.C0", "Demencia no especificada, grave, sin alteración del comportamiento, alteración psicótica, alteración del estado de ánimo ni ansiedad", "demencia", ""],
  ["F03.C11", "Demencia no especificada, grave, con agitación", "demencia agitación", ""],
  ["F03.C18", "Demencia no especificada, grave, con otro tipo de alteración del comportamiento", "demencia conducta", ""],
  ["F03.C2", "Demencia no especificada, grave, con alteración psicótica", "demencia psicosis delirios alucinaciones", ""],
  ["F03.C3", "Demencia no especificada, grave, con alteración del estado de ánimo", "demencia depresión", ""],
  ["F03.C4", "Demencia no especificada, grave, con ansiedad", "demencia ansiedad", ""],
  ["L89.151", "Úlcera por presión en región sacra, estadio I", "UPP escara sacro", ""],
  ["L89.152", "Úlcera por presión en región sacra, estadio II", "UPP escara sacro", ""],
  ["L89.153", "Úlcera por presión en región sacra, estadio III", "UPP escara sacro", ""],
  ["L89.154", "Úlcera por presión en región sacra, estadio IV", "UPP escara sacro", ""],
  ["L89.150", "Úlcera por presión en región sacra, no estadiable", "UPP escara sacro", ""],
  ["L89.156", "Daño de tejido profundo por presión en región sacra", "UPP escara sacro", ""],
  ["L89.159", "Úlcera por presión en región sacra, estadio no especificado", "UPP escara sacro", ""],
  ["L89.211", "Úlcera por presión en cadera derecha, estadio I", "UPP escara trocánter", ""],
  ["L89.212", "Úlcera por presión en cadera derecha, estadio II", "UPP escara trocánter", ""],
  ["L89.213", "Úlcera por presión en cadera derecha, estadio III", "UPP escara trocánter", ""],
  ["L89.214", "Úlcera por presión en cadera derecha, estadio IV", "UPP escara trocánter", ""],
  ["L89.210", "Úlcera por presión en cadera derecha, no estadiable", "UPP escara trocánter", ""],
  ["L89.216", "Daño de tejido profundo por presión en cadera derecha", "UPP escara trocánter", ""],
  ["L89.219", "Úlcera por presión en cadera derecha, estadio no especificado", "UPP escara trocánter", ""],
  ["L89.221", "Úlcera por presión en cadera izquierda, estadio I", "UPP escara trocánter", ""],
  ["L89.222", "Úlcera por presión en cadera izquierda, estadio II", "UPP escara trocánter", ""],
  ["L89.223", "Úlcera por presión en cadera izquierda, estadio III", "UPP escara trocánter", ""],
  ["L89.224", "Úlcera por presión en cadera izquierda, estadio IV", "UPP escara trocánter", ""],
  ["L89.220", "Úlcera por presión en cadera izquierda, no estadiable", "UPP escara trocánter", ""],
  ["L89.226", "Daño de tejido profundo por presión en cadera izquierda", "UPP escara trocánter", ""],
  ["L89.229", "Úlcera por presión en cadera izquierda, estadio no especificado", "UPP escara trocánter", ""],
  ["L89.311", "Úlcera por presión en nalga derecha, estadio I", "UPP escara glúteo", ""],
  ["L89.312", "Úlcera por presión en nalga derecha, estadio II", "UPP escara glúteo", ""],
  ["L89.313", "Úlcera por presión en nalga derecha, estadio III", "UPP escara glúteo", ""],
  ["L89.314", "Úlcera por presión en nalga derecha, estadio IV", "UPP escara glúteo", ""],
  ["L89.310", "Úlcera por presión en nalga derecha, no estadiable", "UPP escara glúteo", ""],
  ["L89.316", "Daño de tejido profundo por presión en nalga derecha", "UPP escara glúteo", ""],
  ["L89.319", "Úlcera por presión en nalga derecha, estadio no especificado", "UPP escara glúteo", ""],
  ["L89.321", "Úlcera por presión en nalga izquierda, estadio I", "UPP escara glúteo", ""],
  ["L89.322", "Úlcera por presión en nalga izquierda, estadio II", "UPP escara glúteo", ""],
  ["L89.323", "Úlcera por presión en nalga izquierda, estadio III", "UPP escara glúteo", ""],
  ["L89.324", "Úlcera por presión en nalga izquierda, estadio IV", "UPP escara glúteo", ""],
  ["L89.320", "Úlcera por presión en nalga izquierda, no estadiable", "UPP escara glúteo", ""],
  ["L89.326", "Daño de tejido profundo por presión en nalga izquierda", "UPP escara glúteo", ""],
  ["L89.329", "Úlcera por presión en nalga izquierda, estadio no especificado", "UPP escara glúteo", ""],
  ["L89.611", "Úlcera por presión en talón derecho, estadio I", "UPP escara", ""],
  ["L89.612", "Úlcera por presión en talón derecho, estadio II", "UPP escara", ""],
  ["L89.613", "Úlcera por presión en talón derecho, estadio III", "UPP escara", ""],
  ["L89.614", "Úlcera por presión en talón derecho, estadio IV", "UPP escara", ""],
  ["L89.610", "Úlcera por presión en talón derecho, no estadiable", "UPP escara", ""],
  ["L89.616", "Daño de tejido profundo por presión en talón derecho", "UPP escara", ""],
  ["L89.619", "Úlcera por presión en talón derecho, estadio no especificado", "UPP escara", ""],
  ["L89.621", "Úlcera por presión en talón izquierdo, estadio I", "UPP escara", ""],
  ["L89.622", "Úlcera por presión en talón izquierdo, estadio II", "UPP escara", ""],
  ["L89.623", "Úlcera por presión en talón izquierdo, estadio III", "UPP escara", ""],
  ["L89.624", "Úlcera por presión en talón izquierdo, estadio IV", "UPP escara", ""],
  ["L89.620", "Úlcera por presión en talón izquierdo, no estadiable", "UPP escara", ""],
  ["L89.626", "Daño de tejido profundo por presión en talón izquierdo", "UPP escara", ""],
  ["L89.629", "Úlcera por presión en talón izquierdo, estadio no especificado", "UPP escara", ""],
  ["L89.511", "Úlcera por presión en tobillo derecho, estadio I", "UPP escara maléolo", ""],
  ["L89.512", "Úlcera por presión en tobillo derecho, estadio II", "UPP escara maléolo", ""],
  ["L89.513", "Úlcera por presión en tobillo derecho, estadio III", "UPP escara maléolo", ""],
  ["L89.514", "Úlcera por presión en tobillo derecho, estadio IV", "UPP escara maléolo", ""],
  ["L89.510", "Úlcera por presión en tobillo derecho, no estadiable", "UPP escara maléolo", ""],
  ["L89.516", "Daño de tejido profundo por presión en tobillo derecho", "UPP escara maléolo", ""],
  ["L89.519", "Úlcera por presión en tobillo derecho, estadio no especificado", "UPP escara maléolo", ""],
  ["L89.521", "Úlcera por presión en tobillo izquierdo, estadio I", "UPP escara maléolo", ""],
  ["L89.522", "Úlcera por presión en tobillo izquierdo, estadio II", "UPP escara maléolo", ""],
  ["L89.523", "Úlcera por presión en tobillo izquierdo, estadio III", "UPP escara maléolo", ""],
  ["L89.524", "Úlcera por presión en tobillo izquierdo, estadio IV", "UPP escara maléolo", ""],
  ["L89.520", "Úlcera por presión en tobillo izquierdo, no estadiable", "UPP escara maléolo", ""],
  ["L89.526", "Daño de tejido profundo por presión en tobillo izquierdo", "UPP escara maléolo", ""],
  ["L89.529", "Úlcera por presión en tobillo izquierdo, estadio no especificado", "UPP escara maléolo", ""],
  ["L89.011", "Úlcera por presión en codo derecho, estadio I", "UPP escara", ""],
  ["L89.012", "Úlcera por presión en codo derecho, estadio II", "UPP escara", ""],
  ["L89.013", "Úlcera por presión en codo derecho, estadio III", "UPP escara", ""],
  ["L89.014", "Úlcera por presión en codo derecho, estadio IV", "UPP escara", ""],
  ["L89.010", "Úlcera por presión en codo derecho, no estadiable", "UPP escara", ""],
  ["L89.016", "Daño de tejido profundo por presión en codo derecho", "UPP escara", ""],
  ["L89.019", "Úlcera por presión en codo derecho, estadio no especificado", "UPP escara", ""],
  ["L89.021", "Úlcera por presión en codo izquierdo, estadio I", "UPP escara", ""],
  ["L89.022", "Úlcera por presión en codo izquierdo, estadio II", "UPP escara", ""],
  ["L89.023", "Úlcera por presión en codo izquierdo, estadio III", "UPP escara", ""],
  ["L89.024", "Úlcera por presión en codo izquierdo, estadio IV", "UPP escara", ""],
  ["L89.020", "Úlcera por presión en codo izquierdo, no estadiable", "UPP escara", ""],
  ["L89.026", "Daño de tejido profundo por presión en codo izquierdo", "UPP escara", ""],
  ["L89.029", "Úlcera por presión en codo izquierdo, estadio no especificado", "UPP escara", ""],
  ["L89.131", "Úlcera por presión en la parte inferior derecha de espalda, estadio I", "UPP escara lumbar", ""],
  ["L89.132", "Úlcera por presión en la parte inferior derecha de espalda, estadio II", "UPP escara lumbar", ""],
  ["L89.133", "Úlcera por presión en la parte inferior derecha de espalda, estadio III", "UPP escara lumbar", ""],
  ["L89.134", "Úlcera por presión en la parte inferior derecha de espalda, estadio IV", "UPP escara lumbar", ""],
  ["L89.130", "Úlcera por presión en la parte inferior derecha de espalda, no estadiable", "UPP escara lumbar", ""],
  ["L89.136", "Daño de tejido profundo por presión en la parte inferior derecha de espalda", "UPP escara lumbar", ""],
  ["L89.139", "Úlcera por presión en la parte inferior derecha de espalda, estadio no especificado", "UPP escara lumbar", ""],
  ["L89.141", "Úlcera por presión en la parte inferior izquierda de espalda, estadio I", "UPP escara lumbar", ""],
  ["L89.142", "Úlcera por presión en la parte inferior izquierda de espalda, estadio II", "UPP escara lumbar", ""],
  ["L89.143", "Úlcera por presión en la parte inferior izquierda de espalda, estadio III", "UPP escara lumbar", ""],
  ["L89.144", "Úlcera por presión en la parte inferior izquierda de espalda, estadio IV", "UPP escara lumbar", ""],
  ["L89.140", "Úlcera por presión en la parte inferior izquierda de espalda, no estadiable", "UPP escara lumbar", ""],
  ["L89.146", "Daño de tejido profundo por presión en la parte inferior izquierda de espalda", "UPP escara lumbar", ""],
  ["L89.149", "Úlcera por presión en la parte inferior izquierda de espalda, estadio no especificado", "UPP escara lumbar", ""],
  ["L89.811", "Úlcera por presión en cabeza, estadio I", "UPP escara", ""],
  ["L89.812", "Úlcera por presión en cabeza, estadio II", "UPP escara", ""],
  ["L89.813", "Úlcera por presión en cabeza, estadio III", "UPP escara", ""],
  ["L89.814", "Úlcera por presión en cabeza, estadio IV", "UPP escara", ""],
  ["L89.810", "Úlcera por presión en cabeza, no estadiable", "UPP escara", ""],
  ["L89.816", "Daño de tejido profundo por presión en cabeza", "UPP escara", ""],
  ["L89.819", "Úlcera por presión en la cabeza, estadio no especificado", "UPP escara", ""],
  ["L89.891", "Úlcera por presión en otros sitios, estadio I", "UPP escara", ""],
  ["L89.892", "Úlcera por presión en otros sitios, estadio II", "UPP escara", ""],
  ["L89.893", "Úlcera por presión en otros sitios, estadio III", "UPP escara", ""],
  ["L89.894", "Úlcera por presión en otros sitios, estadio IV", "UPP escara", ""],
  ["L89.890", "Úlcera por presión en otros sitios, no estadiable", "UPP escara", ""],
  ["L89.896", "Daño de tejido profundo por presión en otros sitios", "UPP escara", ""],
  ["L89.899", "Úlcera por presión en otros sitios, estadio no especificado", "UPP escara", ""],
]
